CREATE TABLE tb_user_types (
    ust_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ust_description VARCHAR(100) NOT NULL UNIQUE,
    ust_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_property_types (
    prt_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    prt_description VARCHAR(100) NOT NULL UNIQUE,
    prt_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_contract_types (
    cot_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    cot_description VARCHAR(100) NOT NULL UNIQUE,
    cot_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tb_payment_types (
    pat_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pat_description VARCHAR(100) NOT NULL UNIQUE,
    pat_created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);